src/java/security/AuthBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package security;

import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 *
 * @author erus
 */
@Named(value = "authBean")
@RequestScoped
public class AuthBean {
    
    
    @Inject 
    private Principal principal;
    @Inject
    private HttpServletRequest request;
    /**
     * Creates a new instance of authBean
     */
    public AuthBean() {
    }

    public Principal getPrincipal() {
        return principal;
    }

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }
    
    public String getPrincipalName() {
        return principal.getName();
    }
    
    public boolean isLogin(){
        String remoteUser  = request.getRemoteUser();
        return (remoteUser != null);
    }
    
    public String logout(){
        try{
            request.logout();
        }
        catch(ServletException ex){
            Logger.getLogger(AuthBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "/main?faces-redirect=true";
    }
    
    public boolean isAdmin(){
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        return context.isUserInRole("admin");
    }
    
    public boolean isSupplier(){
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        return context.isUserInRole("supplier");
    }
    
    public boolean isStudent(){
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        return context.isUserInRole("student");
    }
}

web/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<html  xmlns="http://www.w3.org/1999/xhtml"
               xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
               xmlns:h="http://xmlns.jcp.org/jsf/html"
               xmlns:p="http://primefaces.org/ui"
               xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>朝陽LunchBox</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <h:outputScript library="primefaces" name="jquery/jquery.js" target="head" />
        <h:outputStylesheet library="css" name="style.css"/>
        <h:outputStylesheet library="css" name="header.css"/>
        <h:outputStylesheet library="css" name="menuList.css"/>
        <h:outputStylesheet library="css" name="mealManagePage.css"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        </link>    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
    </h:head>
    
    <h:body>
        <div id="menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <h:link class="navbar-brand" outcome="/main">朝陽LunchBox</h:link>                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                第一餐廳</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{searchBean.supplierFilter('大甲鵝')}" value="大甲鵝"/>
                                </h:form>
                            </div>                            
                        </li>                   
                    </ul>
                    <ul class="navbar-nav mr-auto">                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                第二餐廳</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{searchBean.supplierFilter('金鑽')}" value="金鑽"/>
                                </h:form>
                            </div>                            
                        </li>                   
                    </ul>
                    <ul class="navbar-nav mr-auto">                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                第三餐廳</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{searchBean.supplierFilter('古早味')}" value="古早味"/>
                                </h:form>
                            </div>                            
                        </li>                   
                    </ul>
                    <ui:fragment rendered="#{authBean.student}">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                功能管理</a>                                                    
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{studentOrderBean.salesOrderFilter('全部')}">檢視訂單</h:commandLink>
                                    <h:commandLink class="dropdown-item" action="#{cartBean.randomFind()}">隨機餐點</h:commandLink>
                                </h:form>
                            </div>
                        </li>
                    </ul>
                    </ui:fragment>
                    <ui:fragment rendered="#{authBean.supplier}">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                店家管理</a>                                                    
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown"> 
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{supplierOrderListBean.workOrderFilter('全部')}">店家檢視工單</h:commandLink>
                                    <h:commandLink class="dropdown-item" action="#{mealManageBean.goSupplierManage()}">店家管理菜單</h:commandLink>
                                </h:form>
                            </div>
                        </li>
                    </ul>
                    </ui:fragment>
                    <ui:fragment rendered="#{authBean.admin}">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                管理者選單</a>                                                    
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <h:form>
                                    <h:commandLink class="dropdown-item" action="#{salesOrderManager.salesOrderFilter('全部')}">後端檢視訂單</h:commandLink>
                                    <h:commandLink class="dropdown-item" action="#{workOrderManager.workOrderFilter('全部')}">後端檢視工單</h:commandLink>
                                    <h:commandLink class="dropdown-item" action="#{mealManageBean.adminGoSupplierManage()}">後端管理菜單</h:commandLink>
                                </h:form>
                                <h:link class="dropdown-item" outcome="/admin/supplierSignUp">後端新增店家</h:link>
                            </div>
                        </li>
                    </ul>
                    </ui:fragment>
                    <div class="d-flex flex-row-reverse my-1 " id="search">                    
                        <div class="p-1" id="shopcar"><h:form><h:commandLink action="#{cartBean.viewCart()}">
                                    <p:graphicImage width="40" 
                                                    library="img" name="shopcar.svg" />
                                </h:commandLink></h:form>
                        </div>
                        
                        <div class="p-1" id="keyword" >                            
                            <h:form>
                                <div class="input-group">
                                    <h:inputText class="form-control" value="#{searchBean.search}"/>
                                    <div class="input-group-append">
                                        <h:commandButton style="background-color: #ff9224; border:1px white solid" class="btn btn-outline-secondaryl"  value="搜尋" action="#{searchBean.search()}"/>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                        
<!--                        <div class="p-1" id="condition">
                            <h:form>
                                <h:selectOneMenu class="btn btn-secondary dropdown-toggle" style="background-color:#ff9224; border:1px white solid;padding: 6px">
                                    <f:selectItem itemValue="" itemLabel="評價" /> 
                                    <f:selectItem itemValue="" itemLabel="類別" />
                                    <f:selectItem itemValue="" itemLabel="關鍵字" />
                                </h:selectOneMenu>
                            </h:form>
                        </div>-->
                        
                        <div class="p-1">
                            <ui:fragment rendered="#{!authBean.login}">
                                <h:form>
                                    <h:commandLink action="/auth/login">
                                        <i class="fas fa-sign-in-alt"></i> 登入
                                    </h:commandLink>
                                </h:form>
                                <h:form>
                                    <h:commandLink action="#{registerBean.signUpPage()}">
                                    <i class="fas fa-user-plus"></i> 註冊
                                    </h:commandLink>
                                </h:form>
                            </ui:fragment>
                            <ui:fragment rendered="#{authBean.login}">
                                <h:outputText id="userName" value="#{authBean.principalName}" />
                                <h:form>
                                    <h:commandLink action="#{authBean.logout}" >
                                        <i class="fas fa-sign-out-alt"></i>
                                        登出 
                                    </h:commandLink>
                                </h:form>
                            </ui:fragment>
                        </div>
                        
                    </div>
                </div>
            </nav>
        </div>
        <footer class="fixed-bottom">版權所有,仿冒必究</footer>
        <ui:insert name="contentArea"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </h:body>

</html>